[package]
name = "xr-2000"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
bitfields = "1"
byteorder = "1"
hexdump = "0.1"
rand = "0.9"
regex = "1"
serde = {version = "1", features = ["derive"] }
serde_json = "1"